-- 음식종류별로 즐겨찾기수가 가장 많은 식당
--  음식 종류를 기준으로 내림차순 정렬


WITH TMP AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAB
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT * FROM TMP)
ORDER BY 1 DESC;


