-- 여자, 12세 이하
-- 전화번호가 NULL 이면 NONE
-- 나이 기준 내림차순, 이름 기준 오름차순

SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME;