-- 각 아이스크림 성분 타입과 성분 타입에 대한 아이스크림의 총주문
-- 총주문량이 작은 순서대

SELECT b.INGREDIENT_TYPE, SUM(a.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF a
INNER JOIN ICECREAM_INFO b
ON a.FLAVOR = b.FLAVOR
GROUP BY b.INGREDIENT_TYPE
ORDER BY 2;