-- 2022년 1월의 카테고리 별 도서 판매량을 합산하
--  카테고리명을 기준으로 오름차순 정렬


WITH TMP AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE MONTH(SALES_DATE) = 1 AND YEAR(SALES_DATE) = 2022
    GROUP BY BOOK_ID
)


SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK a
INNER JOIN TMP b
ON a.BOOK_ID = b.BOOK_ID
GROUP BY CATEGORY
ORDER BY 1;
