WITH
DISCOUNT AS (
    SELECT DURATION_TYPE, 1-DISCOUNT_RATE*0.01 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
),

TMP AS (
    SELECT
        HISTORY_ID,
        DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE)+1 AS DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    JOIN CAR_RENTAL_COMPANY_CAR USING(CAR_ID)
    WHERE CAR_TYPE = '트럭'
)

SELECT
    HISTORY_ID,
    CASE
        WHEN DIFF >= 90 THEN ROUND(DAILY_FEE * DIFF * (SELECT DISCOUNT_RATE FROM DISCOUNT WHERE DURATION_TYPE LIKE '9%'))
        WHEN DIFF >= 30 THEN ROUND(DAILY_FEE * DIFF * (SELECT DISCOUNT_RATE FROM DISCOUNT WHERE DURATION_TYPE LIKE '3%'))
        WHEN DIFF >= 7 THEN ROUND(DAILY_FEE * DIFF * (SELECT DISCOUNT_RATE FROM DISCOUNT WHERE DURATION_TYPE LIKE '7%'))
        ELSE DAILY_FEE * DIFF
    END AS FEE
FROM TMP
ORDER BY 2 DESC, 1 DESC

