-- 평균 대여 기간이 7일 이상인 자동차
--  평균 대여 기간은 소수점 두번째 자리에서 반올림
-- 결과는 평균 대여 기간을 기준으로 내림차순 정렬해주시고, 평균 대여 기간이 같으면 자동차 ID를 기준으로 내림차순 정렬

WITH NEW_TABLE AS (
    SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)), 1) AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
)

SELECT CAR_ID, AVERAGE_DURATION + 1
FROM NEW_TABLE
WHERE AVERAGE_DURATION >= 6
ORDER BY 2 DESC, 1 DESC


--
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)), 1) + 1 AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(DATEDIFF(END_DATE, START_DATE)), 1) >= 6
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;
