-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람
--  총거래금액을 기준으로 오름차순 정렬

WITH USERS AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)

SELECT USER_ID, NICKNAME, b.TOTAL AS TOTAL_SALES
FROM USED_GOODS_USER a
INNER JOIN USERS b
ON a.USER_ID = b.WRITER_ID
ORDER BY 3