-- 아이템의 희귀도가 'RARE'인 아이템들의 모든 다음 업그레이드 아이템의 [아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME), 아이템의 희귀도(RARITY)를 출력]
-- 아이템 ID를 기준으로 내림차순 정렬

WITH JOINED_TABLE AS (
    SELECT
        a.ITEM_ID AS ITEM_ID,
        a.ITEM_NAME AS ITEM_NAME,
        a.RARITY AS RARITY,
        b.PARENT_ITEM_ID AS PARENT_ITEM_ID
    FROM ITEM_INFO a
    INNER JOIN ITEM_TREE b
    ON a.ITEM_ID = b.ITEM_ID
)


SELECT ITEM_ID, ITEM_NAME, RARITY
FROM JOINED_TABLE
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY 1 DESC;
