-- 평균 길이는 소수점 3째자리에서 반올
-- 10cm 이하의 물고기들은 10cm 로 취급

WITH NEW_FISH_INFO AS (
    SELECT COALESCE(LENGTH, 10) AS LENGTH
    FROM FISH_INFO
)

SELECT ROUND(AVG(LENGTH), 2) AS AVERAGE_LENGTH
FROM NEW_FISH_INFO;