-- 평균 길이가 33cm 이상인 물고기들을 종류별로 분류
-- 물고기 종류에 대해 오름차순으로 정렬
-- 10cm이하의 물고기들은 10cm로 취급하여 평균 길이를 구해주세요.

WITH TMP AS (
    SELECT FISH_TYPE, AVG(IFNULL(LENGTH, 10)) AS AVG_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT count(a.FISH_TYPE) AS FISH_COUNT, MAX(a.LENGTH) AS MAX_LENGTH, a.FISH_TYPE
FROM FISH_INFO a
INNER JOIN TMP b
ON a.FISH_TYPE = b.FISH_TYPE AND b.AVG_LENGTH >= 33
GROUP BY FISH_TYPE
ORDER BY 3;


--
SELECT count(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) >= 33
ORDER BY 3