-- 3세대의 대장균의 ID(ID) 를 출력
--  대장균의 ID 에 대해 오름차순 정렬

-- PARENT_ID 가 NULL 인 얘들을 PARENT_ID 로 갖는 얘들이 2세대.
-- 걔들을 PARENT_ID 로 갖는 얘들이 3세대

WITH GEN2 AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL)
)

SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (SELECT ID FROM GEN2)
ORDER BY 1