--  ID에 대해 오름차순
-- 부모의 형질을 모두 보유한

SELECT a.ID, a.GENOTYPE, b.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA a
INNER JOIN ECOLI_DATA b
ON a.PARENT_ID = b.ID
WHERE a.GENOTYPE & b.GENOTYPE = b.GENOTYPE
ORDER BY 1;